% Returns budget deficit generated by given tax regime -- the root of this
% function corresponds to a balanced budget. 

function result = deficit(wArray, tax)

[yArray,cArray] = ystar(wArray,tax);

result = sum(cArray) - sum(yArray);
